---
title: "mason analysis"
author: "Noam Altman-Kurosaki"
date: "2024-11-08"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls()) # clean up
# install.packages("librarian")
librarian::shelf(knitr, here, car, glmmTMB, MuMIn, DHARMa, performance, effects, emmeans, ggplot2, ggpubr)

```


```{r read data}
data <- read.csv(here::here("data", "hala_data.csv"), stringsAsFactors = T)
str(data) 
# large sapling ratio is numeric, not integer - can't do Poisson

hist(data$Larger_sapling_ratio ) # two notable outliers

# removing both outliers 
data_sub <- data[data$Larger_sapling_ratio  < 20,]

```


```{r fit model}
mod <- glmmTMB(Larger_sapling_ratio  ~ Hala_scale*Canopy_coverage + Hala_scale*Invasive_understory + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data_sub, na.action = na.pass)
plot(simulateResiduals(mod)) # no issues w/ model assumptions
summary(mod) # zi component is non-significant (z = 0.31, P = 0.753), low variance in random effects
Anova(mod)
#                                 Chisq Df Pr(>Chisq)  
# Hala_scale                     3.0124  1    0.08263 .
# Canopy_coverage                0.6114  1    0.43427  
# Invasive_understory            0.3809  1    0.53712  
# Hala_scale:Canopy_coverage     0.0256  1    0.87289  
# Hala_scale:Invasive_understory 0.6820  1    0.40890  
r.squaredGLMM(mod) # 0.41, 0.41

canopy_effects <- emmip(mod,  Hala_scale ~ Canopy_coverage, at = list(Canopy_coverage = seq(24,100,0.5)), CIs = T, plotit = F)
understory_effects <- emmip(mod,  Hala_scale ~ Invasive_understory, at = list(Invasive_understory = seq(0,80,1)), CIs = T, plotit = F)



# repeat with full dataset
mod_full <- glmmTMB(Larger_sapling_ratio  ~ Hala_scale*Canopy_coverage + Hala_scale*Invasive_understory + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data, na.action = na.pass)
plot(simulateResiduals(mod_full)) # no issues w/ model assumptions
summary(mod_full) # zi component is non-significant (z = 0.10, P = 0.92), low variance in random effects
Anova(mod_full)

# Response: Larger_sapling_ratio 
#                                            Chisq Df Pr(>Chisq)    
# Hala_scale                      1.4369  1  0.2306403    
# Canopy_coverage                           1.9091  1  0.1670650    
# Invasive_understory                       2.1017  1  0.1471308    
# Hala_scale:Canopy_coverage     13.9282  1  0.0001899 ***
# Hala_scale:Invasive_understory 10.3167  1  0.0013183 ** 
r.squaredGLMM(mod_full) # 0.86, 0.86

# general trends - slopes
emtrends(mod_full, ~ Hala_scale, var = "Canopy_coverage")
# Hala_scale Canopy_coverage.trend     SE  df asymp.LCL asymp.UCL
# N                        -0.0381 0.0108 Inf  -0.05928   -0.0169
# Y                         0.0220 0.0119 Inf  -0.00141    0.0454

emtrends(mod_full, ~ Hala_scale, var = "Invasive_understory")
# Hala_scale Invasive_understory.trend     SE  df asymp.LCL asymp.UCL
# N                             0.0114 0.0200 Inf   -0.0278    0.0506
# Y                             0.2602 0.0748 Inf    0.1135    0.4068


# extract model estimates
canopy_effects_full <- emmip(mod_full,  Hala_scale ~ Canopy_coverage, at = list(Canopy_coverage = seq(7,100,0.5)), CIs = T, plotit = F)
understory_effects_full <- emmip(mod_full,  Hala_scale ~ Invasive_understory, at = list(Invasive_understory = seq(0,80,1)), CIs = T, plotit = F)



mod_summary <- as.data.frame(model.sel(dredge(mod)))
View(mod_summary) # top model includes intercept and hala scale

# subset only models where AICc is less than 2
mod_summary_subset <- mod_summary[mod_summary$delta < 2,]

# write.csv(mod_summary_subset, file = "new_model_no_outliers.csv")

# repeat with full model
mod_summary_outliers <- as.data.frame(model.sel(dredge(mod_full)))
# View(mod_summary_outliers) # top model includes all terms and is best by far - next best model is delta of > 4

# rather than subset models where delta is less than 2, just going to subset the top 4 to illustrate the point
mod_summary_outliers_subset <- mod_summary_outliers[1:4,]

# write.csv(mod_summary_outliers_subset, file = "new_model_with_outliers.csv")





```

```{r plot models not outliers, fig.height=6, fig.width=12}
(canopy_plot <- ggplot() +
  geom_point(data = data_sub, aes(x = Canopy_coverage, y = Larger_sapling_ratio , colour = Hala_scale)) +
  geom_line(data = canopy_effects, aes(x = Canopy_coverage, y = exp(yvar), colour = Hala_scale)) + 
  geom_ribbon(data = canopy_effects, aes(x = Canopy_coverage, ymin = exp(LCL), ymax = exp(UCL), fill = Hala_scale), alpha = 0.3) +
  labs(title = "a.", y = "Larger sapling ratio", x = "Canopy cover (%)") +
  scale_fill_discrete(name = "Hala Scale") +
  scale_colour_discrete(name = "Hala Scale") +
  theme_classic() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom",
        legend.key.size = unit(1.5, 'cm'),
        legend.text = element_text(size=25),
        legend.title = element_text(size=32),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(color = "black", size = 32, face = "plain"),
        axis.text.x = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain")
  )
)

(understory_plot <- ggplot() +
  geom_point(data = data_sub, aes(x = Invasive_understory, y = Larger_sapling_ratio , colour = Hala_scale)) +
  geom_line(data = understory_effects, aes(x = Invasive_understory, y = exp(yvar), colour = Hala_scale)) + 
  geom_ribbon(data = understory_effects,
              aes(x = Invasive_understory, ymin = exp(LCL), ymax = exp(UCL), fill = Hala_scale), alpha = 0.3) +
  labs(title = "b.", y = "", x = "Invasive understory") +
  scale_fill_discrete(name = "Hala Scale") +
  scale_colour_discrete(name = "Hala Scale") +
  theme_classic() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom",
        legend.key.size = unit(1.5, 'cm'),
        legend.text = element_text(size=25),
        legend.title = element_text(size=32),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(color = "black", size = 32, face = "plain"),
        axis.text.x = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain")
  )
)

(no_outliers_panel <- ggarrange(canopy_plot, understory_plot, nrow = 1, ncol = 2, legend = "bottom", common.legend = T))
# ggsave(filename = here::here("output", "no_outliers_model_plot_full.png"),no_outliers_panel, height = 6, width = 13)

# massive confidence intervals make the understory plot largely uninterpretable
```

```{r plot model with outliers, fig.height = 6, fig.width=12}
(canopy_plot_full <- ggplot() +
  geom_point(data = data, aes(x = Canopy_coverage, y = Larger_sapling_ratio , colour = Hala_scale)) +
  geom_line(data = canopy_effects_full, aes(x = Canopy_coverage, y = exp(yvar), colour = Hala_scale)) + 
  geom_ribbon(data = canopy_effects_full, aes(x = Canopy_coverage, ymin = exp(LCL), ymax = exp(UCL), fill = Hala_scale), alpha = 0.3) +
  labs(title = "a.", y = "Larger sapling ratio", x = "Canopy cover (%)") +
  scale_fill_discrete(name = "Hala Scale") +
  scale_colour_discrete(name = "Hala Scale") +

  theme_classic() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom",
        legend.key.size = unit(1.5, 'cm'),
        legend.text = element_text(size=25),
        legend.title = element_text(size=32),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(color = "black", size = 32, face = "plain"),
        axis.text.x = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain")
  )
)

(understory_plot_full <- ggplot() +
  geom_point(data = data, aes(x = Invasive_understory, y = Larger_sapling_ratio , colour = Hala_scale)) +
  geom_line(data = understory_effects_full, aes(x = Invasive_understory, y = exp(yvar), colour = Hala_scale)) + 
  geom_ribbon(data = understory_effects_full,
              aes(x = Invasive_understory, ymin = exp(LCL), ymax = exp(UCL), fill = Hala_scale), alpha = 0.3) +
  labs(title = "b.", y = "", x = "Invasive understory") +
  scale_fill_discrete(name = "Hala Scale") +
  scale_colour_discrete(name = "Hala Scale") +

  theme_classic() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom",
        legend.key.size = unit(1.5, 'cm'),
        legend.text = element_text(size=25),
        legend.title = element_text(size=32),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(color = "black", size = 32, face = "plain"),
        axis.text.x = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain")
  )
)

(outliers_panel <- ggarrange(canopy_plot_full, understory_plot_full, nrow = 1, ncol = 2, legend = "bottom", common.legend = T))
# uncertainty in invasive understory again makes this meaningless
# ggsave(filename = here::here("output", "outliers_model_plot_full.png"),outliers_panel, height = 6, width = 13)
```

```{r alternative hala models, fig.height = 10, fig.width=10}
mod_hala <- glmmTMB(Larger_sapling_ratio  ~ Hala_scale + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data_sub, na.action = na.pass)
summary(mod_hala)
Anova(mod_hala) 
# Hala_scale X2 = 6.6126, P = 0.01013 *


mod_us <- glmmTMB(Larger_sapling_ratio  ~ Invasive_understory + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data_sub, na.action = na.pass)
summary(mod_us)
plot(simulateResiduals(mod_us)) # some issues in lower quartile, but not too bad
Anova(mod_us)
#                      Chisq Df Pr(>Chisq)
# Invasive_understory 1.9903  1     0.1583

mod_null <- glmmTMB(Larger_sapling_ratio  ~ 1 + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data_sub, na.action = na.pass)
summary(mod_null)
# Conditional model:
#             Estimate Std. Error z value Pr(>|z|)  
# (Intercept)   0.5168     0.2654   1.947   0.0515 
plot(simulateResiduals(mod_null)) # no issues

mod_hs_us <- glmmTMB(Larger_sapling_ratio  ~ Hala_scale + Invasive_understory + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data_sub, na.action = na.pass)
summary(mod_hs_us)
plot(simulateResiduals(mod_hs_us)) # some issues in lower quantile but still not too bad
Anova(mod_hs_us)
#                      Chisq Df Pr(>Chisq)  
# Hala_scale          2.8318  1    0.09242 .
# Invasive_understory 0.4494  1    0.50261  

mod_hs_us_x <- glmmTMB(Larger_sapling_ratio  ~ Hala_scale*Invasive_understory + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data_sub, na.action = na.pass)
summary(mod_hs_us_x)
plot(simulateResiduals(mod_hs_us_x)) # some issues in lower quantile but still not too bad
Anova(mod_hs_us_x)

#                                 Chisq Df Pr(>Chisq)  
# Hala_scale                     3.0077  1    0.08287 .
# Invasive_understory            0.4168  1    0.51855  
# Hala_scale:Invasive_understory 0.3452  1    0.55684  

mod_hs_us_cc <- glmmTMB(Larger_sapling_ratio  ~ Hala_scale + Invasive_understory + Canopy_coverage + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data_sub, na.action = na.pass)
summary(mod_hs_us_cc)
plot(simulateResiduals(mod_hs_us_cc)) # no issues
Anova(mod_hs_us_cc)
#                      Chisq Df Pr(>Chisq)  
# Hala_scale          2.9597  1    0.08536 .
# Invasive_understory 0.3955  1    0.52940  
# Canopy_coverage     0.1912  1    0.66191  


```

```{r just hala plot}
# plot of top model
(hala_plot <- ggplot(data_sub) +
  geom_violin(aes(x = Hala_scale, y = Larger_sapling_ratio), draw_quantiles = c(0, 0.25, 0.5, 0.75)) +
  geom_jitter(aes(x = Hala_scale, y = Larger_sapling_ratio), width = 0.1) +
  labs(y = "Larger sapling ratio", x = "Hala scale") +
  theme_classic() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom",
        legend.key.size = unit(1.5, 'cm'),
        legend.text = element_text(size=25),
        legend.title = element_text(size=32),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(color = "black", size = 32, face = "plain"),
        axis.text.x = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain")
  )
)

# ggsave(filename = here::here("output", "hala_only_plot.png"),hala_plot, height = 10, width = 10)
```

```{r small sapling model}
hist(data$Small_sapling_ratio) # bet this is overdispersed
small_mod_1 <- glmmTMB(Small_sapling_ratio  ~ Hala_scale*Canopy_coverage + Hala_scale*Invasive_understory + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data_sub, na.action = na.pass)
plot(simulateResiduals(small_mod_1)) # no issues
summary(small_mod_1) # significant zeo inflated component (z = -6.17, P = 6.8E-10)

small_mod_summary <- as.data.frame(model.sel(dredge(small_mod_1)))
View(small_mod_summary) # top model includes invasive understory and hala scale but no interactions

# subset only models where AICc is less than 2
small_mod_summary_subset <- small_mod_summary[small_mod_summary$delta < 2,]

# write.csv(small_mod_summary_subset, file = "small_sapling_ratio.csv")

# top model
small_mod_2 <- glmmTMB(Small_sapling_ratio  ~ Hala_scale + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data_sub, na.action = na.pass)
summary(small_mod_2) # same results as above for zero inflated component
Anova(small_mod_2) # X2 = 5.3, P = 0.02

(small_sapling_plot <- ggplot(data) +
  geom_violin(aes(x = Hala_scale, y = Small_sapling_ratio), draw_quantiles = c(0, 0.25, 0.5, 0.75)) +
  geom_jitter(aes(x = Hala_scale, y = Small_sapling_ratio), width = 0.1) +
  labs(y = "Small sapling ratio", x = "Hala scale") +
  theme_classic() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom",
        legend.key.size = unit(1.5, 'cm'),
        legend.text = element_text(size=25),
        legend.title = element_text(size=32),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(color = "black", size = 32, face = "plain"),
        axis.text.x = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain")
  )
)

# ggsave(filename = here::here("output", "small_sapling_plot.png"),small_sapling_plot, height = 10, width = 10)
```

```{r pre reproductive sapling model}
hist(data$Pre.reproductive_ratio) # possible zero inflation?
reproductive_mod_1 <- glmmTMB(Pre.reproductive_ratio  ~ Hala_scale*Canopy_coverage + Hala_scale*Invasive_understory + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data_sub, na.action = na.pass)
plot(simulateResiduals(reproductive_mod_1)) # no issues a
summary(reproductive_mod_1) # no significant zero inflation z = -0.524, P = 0.6

reproductive_mod_summary <- as.data.frame(model.sel(dredge(reproductive_mod_1)))
View(reproductive_mod_summary) # top model includes just canopy cover

# subset only models where AICc is less than 2
reproductive_mod_summary_subset <- reproductive_mod_summary[reproductive_mod_summary$delta < 2,]
# write.csv(reproductive_mod_summary_subset, file = "pre_reproductive_ratio.csv")



```

```{r alternative reprod models}
# top model
reproductive_mod_2 <- glmmTMB(Pre.reproductive_ratio  ~ Canopy_coverage + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data_sub, na.action = na.pass)
summary(reproductive_mod_2) # same zero inflated component as before
Anova(reproductive_mod_2) 
#                 Chisq Df Pr(>Chisq)  
# Canopy_coverage 3.593  1    0.05802 .

# null model - 2nd best
reproductive_mod_null <- glmmTMB(Pre.reproductive_ratio  ~ 1 + (1|Location), family = ziGamma("log"), ziformula = ~1, data = data_sub, na.action = na.pass)
summary(reproductive_mod_null) # same zero inflated component as before
# Conditional model:
#             Estimate Std. Error z value Pr(>|z|)
# (Intercept)  0.03883    0.28629   0.136    0.892
```

```{r top model plot}

reprod_canopy_effects <- emmip(reproductive_mod_2, ~ Canopy_coverage, at = list(Canopy_coverage = seq(24,100,0.5)), CIs = T, plotit = F)

(pre_reproductive_plot <- ggplot() +
  geom_point(data = data, aes(x = Canopy_coverage, y = Small_sapling_ratio)) +
  geom_line(data = reprod_canopy_effects, aes(x = Canopy_coverage, y = exp(yvar))) +
  geom_ribbon(data = reprod_canopy_effects, aes(x = Canopy_coverage, ymin = exp(LCL), ymax = exp(UCL)), alpha = 0.4) +
  labs(y = "Small sapling ratio", x = "Hala scale") +
  theme_classic() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom",
        legend.key.size = unit(1.5, 'cm'),
        legend.text = element_text(size=25),
        legend.title = element_text(size=32),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(color = "black", size = 32, face = "plain"),
        axis.text.x = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain")
  )
)
# ggsave(filename = here::here("output", "pre_reproductive_plot.png"),pre_reproductive_plot, height = 10, width = 10)
```